### ISSUE TITLE
User Story #6 Create Post

### ISSUE THREAD

**Issue by janneserichsen** [janneserichsen/CapStone-Graffstar#10]
## Value Proposition

As a User i want to be able to create my own Posts 
so that i can share my own Work with other Users 

## Description
<img width="252" alt="Bildschirmfoto 2023-01-31 um 15 25 16" src="https://user-images.githubusercontent.com/118190990/215787500-dcec4fd4-8dc7-4d20-8b12-f38ff0134bc4.png">

<img width="712" alt="Bildschirmfoto 2023-01-31 um 15 25 41" src="https://user-images.githubusercontent.com/118190990/215787524-b9585e63-d02b-4bb1-a7eb-1fe8e30147b5.png">

## Acceptance Criteria

- [ ] Input for User Name
- [ ] Input for Location
- [ ] Image Input
- [ ] Seperated Page for this 
- [ ]  there is an input type="file" which works with an url for now
- [ ] a Link to "new Post" is displayed on the discoverpage
- [ ] After Creating the Post you get an Alert and get Linked to the Discoverpage

## Tasks

- [ ] Create a new index.js in newPost Folder
- [ ] Create a button in the Discoverpage that Links to the newPost Index
- [ ] Create Name, Location and Image input
- [ ] Create Submit Button
- [ ] Display the created Information on the Discoverpage

## Complexity

L

**Comment by marcterre** [comment]
Hey Jannes, you wirframes are a little bit irritating, i guess you are using excalidraw. There you can mark the shapes you need and export them as image by clicking the burger menu at the top left...
I know from your task that you can click a button on the discoverpage which leads to a "creating new post"-page but thats not clear if i look on your acceptance criteria. Maybe dont write "sepereated page for this" but
- [ ] a Link to "new Post" is displayed on the discoverpage

You dont have to use a Button, a Link works pretty fine.
In your wireframe it looks like the image input works with a url? So you dont implement an image upload yet? You could describe this more. This should be mentioned in you acceptance criteria, for example:
- [ ] there is an input type="file" which works with an url for now

Is there a preview below the image input? Can you also desribe this more?

Feel free to ask if something is not clear 🙂
