### ISSUE TITLE
Introduction Page at the Beginning us#7

### ISSUE THREAD

**Issue by janneserichsen** [janneserichsen/CapStone-Graffstar#12]
## Value Proposition

As i User i want to have a nice little Introduction of the App
and what its used for so that i get like a little Walk through

## Description
<img width="306" alt="Bildschirmfoto 2023-02-09 um 10 32 25" src="https://user-images.githubusercontent.com/118190990/217773942-3dbfaf90-b667-4047-9767-dbf369084b94.png">

## Acceptance Criteria

- [ ]New Page at the Beginning
- [ ] Short Introduction about the App
- [ ] Button to Link to the Discover Page

## Tasks

- [ ] Create new Page at index.js
- [ ] Create Introduction Text
- [ ] Create Button with Link to Discover.js

## Complexity

S
