### ISSUE TITLE
User Story #4

### ISSUE THREAD

**Issue by janneserichsen** [janneserichsen/CapStone-Graffstar#6]
## Value Proposition

As a User I want to see my own Work on a Profile Page 
as a Place where i can see my own Information
so that i can check everythingh about me and so that other People can see my Info too

## Description
<img width="185" alt="Bildschirmfoto 2023-01-27 um 10 34 22" src="https://user-images.githubusercontent.com/118190990/215054565-9ed1eaea-c4ed-41ad-b8be-fe629721bca8.png">

## Acceptance Criteria

- [ ] You can see a Profile Picture with Captions like my Crew and my Location and Name
- [ ] Also that you can see the Work of the User

## Tasks

- [ ] Create Profile Page
- [ ] Create a Profile Picture and some Captions for the Picture like the User Location
- [ ] Create some Images on the Profile Page
- [ ] Put the Navbar in to the Profile Page

**Comment by AGeck113** [comment]
Hi Jannes, 
at the value Proposition, it is not clear, if you want to display both things on one page or on two. Could you be more specific here? Like "I want to see my data and my work on my profile page" Or something like that?
In the Tasks you need to be more precise also. You just say create dummy profile and dummy pictures.
You don´t write anything about how the dummy data should be displayed.
Do you already have a profile page or do you have to create it?
Where and how are the pictures you want to create be saved? Maybe an array?
The Complexity is also missing here.
