### ISSUE TITLE
user story #5

### ISSUE THREAD

**Issue by janneserichsen** [janneserichsen/CapStone-Graffstar#9]
## Value Proposition

As a User i want to Comment under other Users Post
so that i can give them some Advice or somethingh other.
And i want to be able to edit or delete my Comment

## Description
<img width="187" alt="Bildschirmfoto 2023-01-30 um 10 18 09" src="https://user-images.githubusercontent.com/118190990/215436414-f2fb2fb6-dceb-4c76-ae45-734c9c4d47ff.png">

## Acceptance Criteria

- [ ] Comment Input for each Picture
- [ ] I can delete and edit my Comment
- [ ] ...

## Tasks

- [ ]  create Comment Input
- [ ]  create Section for the Comments 
- [ ]  Call the Comment under every Post

## Complexity

m

**Comment by AstridOttmann** [comment]
Looks good, just same small comments: 
- try to shorten your value proposition, i. e. I want to  leave comments to the posts
so that I can share my opinion 
- in your tasks I miss the implementation of functionality
